### ISSUE TITLE
Is NBExplorer mandatory?

### ISSUE THREAD

**Issue by dangershony** [joemphilips/NRustLightning#19]
Or perhaps using directly a fullnode can be supported?

**Comment by joemphilips** [comment]
Hi, sorry for the late reply.

Currently, it is mandatory, but I'm planning to remove it in the next iteration.
It is there because originally I wanted to support Altchains, but ended up not because rust-lightning has no plan to support it.

**Comment by dangershony** [comment]
Thanks good to know.
